SELECT 

	 A.F0132_CROSS_KEY'account'
	,A.R_TR_TR_AC_CODE'code'
	,A.R_TR_DESC'desc'
	,A.R_TR_TOTAL_AMT'amount'
	,B.F0262_PROCEEDS_AMOUNT'proceeds'
	,B.F0148_LATE_CHARGES_DUE_AMOUNT'late'
	,B.F0571_MISC_FEES_DUE_AMOUNT'fees'
	,A.R_TR_PRIN'prin pmt'
	,CONVERT(DATE, A.R_TR_EFF_DTE)'EFF DATE'
	--,ISNULL(C.F0264_DEALER_HOLDBACK, 0)

FROM

	[SHAW_HISTORY].[dbo].[DWR_RETAIL_TRAN_HISTORY] A
	LEFT JOIN SHAW_EOD.DBO.DWR_RETAIL B ON  B.F0132_CROSS_KEY = A.F0132_CROSS_KEY
	LEFT JOIN SHAW_EOD.DBO.DWR_RETAIL C ON C.F0132_CROSS_KEY = A.F0132_CROSS_KEY

WHERE 

	SUBSTRING(A.F0132_CROSS_KEY, 1, 11) IN ('17273190002',
'17329150002',
'17372670003')

	
	AND R_TR_DESC IN ('DDIS','ADIS','WPAY','UGAP','UWAR','DRSV','LTCA','0NF2','REPO',
					  'IMPO','GPSR','DHFL','PNM1','PNM2','PYNM','MNYG','WUQC','PYED',
					  'WSTU','CFPW','CFPM','PYC','PYAU','PYDL','PYED','PYBK','PYCO',
					  'BDR','AULW','GAPW','PYDU','DHBB', 'NSF') 

	--AND ISNULL(C.F0264_DEALER_HOLDBACK, 0) > '0'

ORDER BY 1
